import = [
	"~/.config/alacritty/catppuccin-frappe.toml"
]
[font]
#normal = {family = "CozetteVector", style = "regular"}
#bold = {family = "CozetteVector", style = "bold"}
#italic = {family = "CozetteVector", style = "italic"}
#bold_italic= {family = "CozetteVector", style = "bold italic"}
normal = {family = "JetBrains Mono", style = "regular"}
bold = {family = "JetBrains Mono", style = "bold"}
italic = {family = "JetBrains Mono", style = "italic"}
bold_italic= {family = "JetBrains Mono", style = "bold italic"}
size = 13.0
offset.x = 0  # For letter spacing (default: 0)
offset.y = 0 # For line spacing (default: 0)

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity=1
